<?php
print "
<html>

<head>
<meta http-equiv='Content-Language' content='pl'>
<meta name='GENERATOR' content='kay'>
<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-2'>
<meta name='keywords' content='fajny bank, duzy bank, maly bank, vabank'>
<meta name='Description' content='vaBank - jedyny taki bank'>
<link rel='stylesheet' href='lib/fonts.css' type='text/css'> 
<title>vaBank - jedyny taki Bank</title>
</head>

<body text='#000000' bgcolor='#FFFFFF'>

<table border='0' style='border-collapse: collapse' width='100%' height='100%'>
  <tr>
    <td width='100' height='100' bgcolor='#C0C0C0'>
    <p align='left'>
    <a href=index.html><img border='0' src='gfx/logo-grey.gif'></a></td>
    <td height='100' bgcolor='#C0C0C0'>
    <p align='right'>&nbsp;Jedyny taki bank</td>
  </tr>
  <tr>
    <td width='100%' valign='top' colspan='2'>
";
?>
    